// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/app.dart';
import 'api/hub.dart';
import 'api/sender.dart';

import 'dart:async';
import 'dart:convert';

import 'frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  RustStreamSink<DiscoveryEventDto>
  dco_decode_StreamSink_discovery_event_dto_Sse(dynamic raw);

  @protected
  RustStreamSink<HubEventDto> dco_decode_StreamSink_hub_event_dto_Sse(
    dynamic raw,
  );

  @protected
  RustStreamSink<SenderStatusDto> dco_decode_StreamSink_sender_status_dto_Sse(
    dynamic raw,
  );

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  AppInfo dco_decode_app_info(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  HubInfoDto dco_decode_box_autoadd_hub_info_dto(dynamic raw);

  @protected
  SenderStartDto dco_decode_box_autoadd_sender_start_dto(dynamic raw);

  @protected
  SettingsDto dco_decode_box_autoadd_settings_dto(dynamic raw);

  @protected
  SourceDto dco_decode_box_autoadd_source_dto(dynamic raw);

  @protected
  CapabilitiesDto dco_decode_capabilities_dto(dynamic raw);

  @protected
  CaptureAppDto dco_decode_capture_app_dto(dynamic raw);

  @protected
  CaptureSourceDto dco_decode_capture_source_dto(dynamic raw);

  @protected
  DiscoveryEventDto dco_decode_discovery_event_dto(dynamic raw);

  @protected
  double dco_decode_f_32(dynamic raw);

  @protected
  HubEventDto dco_decode_hub_event_dto(dynamic raw);

  @protected
  HubInfoDto dco_decode_hub_info_dto(dynamic raw);

  @protected
  HubStatusDto dco_decode_hub_status_dto(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<CaptureAppDto> dco_decode_list_capture_app_dto(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<SourceDto> dco_decode_list_source_dto(dynamic raw);

  @protected
  List<TrustedPeerDto> dco_decode_list_trusted_peer_dto(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  PairingInfoDto dco_decode_pairing_info_dto(dynamic raw);

  @protected
  PairingUriDto dco_decode_pairing_uri_dto(dynamic raw);

  @protected
  SenderStartDto dco_decode_sender_start_dto(dynamic raw);

  @protected
  SenderStatusDto dco_decode_sender_status_dto(dynamic raw);

  @protected
  SettingsDto dco_decode_settings_dto(dynamic raw);

  @protected
  SourceDto dco_decode_source_dto(dynamic raw);

  @protected
  TrustedPeerDto dco_decode_trusted_peer_dto(dynamic raw);

  @protected
  int dco_decode_u_16(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  RustStreamSink<DiscoveryEventDto>
  sse_decode_StreamSink_discovery_event_dto_Sse(SseDeserializer deserializer);

  @protected
  RustStreamSink<HubEventDto> sse_decode_StreamSink_hub_event_dto_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<SenderStatusDto> sse_decode_StreamSink_sender_status_dto_Sse(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AppInfo sse_decode_app_info(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  HubInfoDto sse_decode_box_autoadd_hub_info_dto(SseDeserializer deserializer);

  @protected
  SenderStartDto sse_decode_box_autoadd_sender_start_dto(
    SseDeserializer deserializer,
  );

  @protected
  SettingsDto sse_decode_box_autoadd_settings_dto(SseDeserializer deserializer);

  @protected
  SourceDto sse_decode_box_autoadd_source_dto(SseDeserializer deserializer);

  @protected
  CapabilitiesDto sse_decode_capabilities_dto(SseDeserializer deserializer);

  @protected
  CaptureAppDto sse_decode_capture_app_dto(SseDeserializer deserializer);

  @protected
  CaptureSourceDto sse_decode_capture_source_dto(SseDeserializer deserializer);

  @protected
  DiscoveryEventDto sse_decode_discovery_event_dto(
    SseDeserializer deserializer,
  );

  @protected
  double sse_decode_f_32(SseDeserializer deserializer);

  @protected
  HubEventDto sse_decode_hub_event_dto(SseDeserializer deserializer);

  @protected
  HubInfoDto sse_decode_hub_info_dto(SseDeserializer deserializer);

  @protected
  HubStatusDto sse_decode_hub_status_dto(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<CaptureAppDto> sse_decode_list_capture_app_dto(
    SseDeserializer deserializer,
  );

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<SourceDto> sse_decode_list_source_dto(SseDeserializer deserializer);

  @protected
  List<TrustedPeerDto> sse_decode_list_trusted_peer_dto(
    SseDeserializer deserializer,
  );

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  PairingInfoDto sse_decode_pairing_info_dto(SseDeserializer deserializer);

  @protected
  PairingUriDto sse_decode_pairing_uri_dto(SseDeserializer deserializer);

  @protected
  SenderStartDto sse_decode_sender_start_dto(SseDeserializer deserializer);

  @protected
  SenderStatusDto sse_decode_sender_status_dto(SseDeserializer deserializer);

  @protected
  SettingsDto sse_decode_settings_dto(SseDeserializer deserializer);

  @protected
  SourceDto sse_decode_source_dto(SseDeserializer deserializer);

  @protected
  TrustedPeerDto sse_decode_trusted_peer_dto(SseDeserializer deserializer);

  @protected
  int sse_decode_u_16(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_discovery_event_dto_Sse(
    RustStreamSink<DiscoveryEventDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_hub_event_dto_Sse(
    RustStreamSink<HubEventDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_sender_status_dto_Sse(
    RustStreamSink<SenderStatusDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_app_info(AppInfo self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_hub_info_dto(
    HubInfoDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_sender_start_dto(
    SenderStartDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_settings_dto(
    SettingsDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_source_dto(
    SourceDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_capabilities_dto(
    CapabilitiesDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_capture_app_dto(CaptureAppDto self, SseSerializer serializer);

  @protected
  void sse_encode_capture_source_dto(
    CaptureSourceDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_discovery_event_dto(
    DiscoveryEventDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer);

  @protected
  void sse_encode_hub_event_dto(HubEventDto self, SseSerializer serializer);

  @protected
  void sse_encode_hub_info_dto(HubInfoDto self, SseSerializer serializer);

  @protected
  void sse_encode_hub_status_dto(HubStatusDto self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_capture_app_dto(
    List<CaptureAppDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_source_dto(
    List<SourceDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_trusted_peer_dto(
    List<TrustedPeerDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_pairing_info_dto(
    PairingInfoDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_pairing_uri_dto(PairingUriDto self, SseSerializer serializer);

  @protected
  void sse_encode_sender_start_dto(
    SenderStartDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_sender_status_dto(
    SenderStatusDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_settings_dto(SettingsDto self, SseSerializer serializer);

  @protected
  void sse_encode_source_dto(SourceDto self, SseSerializer serializer);

  @protected
  void sse_encode_trusted_peer_dto(
    TrustedPeerDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {}
