// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/app.dart';
import 'api/hub.dart';
import 'api/sender.dart';

import 'dart:async';
import 'dart:convert';

import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiAppInitBridge();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.13.0';

  @override
  int get rustContentHash => 1934918521;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'hfa_ffi',
        ioDirectory: '../core/hfa-ffi/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Stream<DiscoveryEventDto> crateApiSenderDiscoverHubs();

  Future<void> crateApiAppForgetPeer({required String deviceId});

  Future<SettingsDto> crateApiAppGetSettings();

  Future<void> crateApiHubHubCancelPairing();

  Stream<HubEventDto> crateApiHubHubEvents();

  Future<PairingInfoDto?> crateApiHubHubPairingStatus();

  Future<void> crateApiHubHubSetGain({
    required int streamId,
    required double gain,
  });

  Future<void> crateApiHubHubSetMasterGain({required double gain});

  Future<void> crateApiHubHubSetMuted({
    required int streamId,
    required bool muted,
  });

  Future<void> crateApiHubHubSetPriority({
    required int streamId,
    required bool priority,
  });

  Future<List<SourceDto>> crateApiHubHubSources();

  Future<HubStatusDto> crateApiHubHubStart();

  Future<PairingInfoDto> crateApiHubHubStartPairing();

  Future<HubStatusDto> crateApiHubHubStatus();

  Future<void> crateApiHubHubStop();

  Future<AppInfo> crateApiAppInitApp({
    required String dataDir,
    String? deviceName,
  });

  Future<void> crateApiAppInitBridge();

  Future<List<CaptureAppDto>> crateApiSenderListCaptureApps();

  Future<List<String>> crateApiAppListOutputDevices();

  Future<PairingUriDto> crateApiAppParsePairingUri({required String uri});

  Stream<SenderStatusDto> crateApiSenderSenderEvents();

  Future<void> crateApiSenderSenderStart({required SenderStartDto request});

  Future<SenderStatusDto> crateApiSenderSenderStatus();

  Future<void> crateApiSenderSenderStop();

  Future<void> crateApiSenderStopDiscovery();

  Future<List<TrustedPeerDto>> crateApiAppTrustedPeers();

  Future<void> crateApiAppUpdateSettings({required SettingsDto settings});
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Stream<DiscoveryEventDto> crateApiSenderDiscoverHubs() {
    final sink = RustStreamSink<DiscoveryEventDto>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_StreamSink_discovery_event_dto_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 1,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: sse_decode_AnyhowException,
          ),
          constMeta: kCrateApiSenderDiscoverHubsConstMeta,
          argValues: [sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiSenderDiscoverHubsConstMeta =>
      const TaskConstMeta(debugName: "discover_hubs", argNames: ["sink"]);

  @override
  Future<void> crateApiAppForgetPeer({required String deviceId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(deviceId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiAppForgetPeerConstMeta,
        argValues: [deviceId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAppForgetPeerConstMeta =>
      const TaskConstMeta(debugName: "forget_peer", argNames: ["deviceId"]);

  @override
  Future<SettingsDto> crateApiAppGetSettings() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_settings_dto,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiAppGetSettingsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAppGetSettingsConstMeta =>
      const TaskConstMeta(debugName: "get_settings", argNames: []);

  @override
  Future<void> crateApiHubHubCancelPairing() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiHubHubCancelPairingConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiHubHubCancelPairingConstMeta =>
      const TaskConstMeta(debugName: "hub_cancel_pairing", argNames: []);

  @override
  Stream<HubEventDto> crateApiHubHubEvents() {
    final sink = RustStreamSink<HubEventDto>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_StreamSink_hub_event_dto_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 5,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: sse_decode_AnyhowException,
          ),
          constMeta: kCrateApiHubHubEventsConstMeta,
          argValues: [sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiHubHubEventsConstMeta =>
      const TaskConstMeta(debugName: "hub_events", argNames: ["sink"]);

  @override
  Future<PairingInfoDto?> crateApiHubHubPairingStatus() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_box_autoadd_pairing_info_dto,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiHubHubPairingStatusConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiHubHubPairingStatusConstMeta =>
      const TaskConstMeta(debugName: "hub_pairing_status", argNames: []);

  @override
  Future<void> crateApiHubHubSetGain({
    required int streamId,
    required double gain,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_32(streamId, serializer);
          sse_encode_f_32(gain, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiHubHubSetGainConstMeta,
        argValues: [streamId, gain],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiHubHubSetGainConstMeta => const TaskConstMeta(
    debugName: "hub_set_gain",
    argNames: ["streamId", "gain"],
  );

  @override
  Future<void> crateApiHubHubSetMasterGain({required double gain}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_f_32(gain, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiHubHubSetMasterGainConstMeta,
        argValues: [gain],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiHubHubSetMasterGainConstMeta =>
      const TaskConstMeta(debugName: "hub_set_master_gain", argNames: ["gain"]);

  @override
  Future<void> crateApiHubHubSetMuted({
    required int streamId,
    required bool muted,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_32(streamId, serializer);
          sse_encode_bool(muted, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiHubHubSetMutedConstMeta,
        argValues: [streamId, muted],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiHubHubSetMutedConstMeta => const TaskConstMeta(
    debugName: "hub_set_muted",
    argNames: ["streamId", "muted"],
  );

  @override
  Future<void> crateApiHubHubSetPriority({
    required int streamId,
    required bool priority,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_32(streamId, serializer);
          sse_encode_bool(priority, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiHubHubSetPriorityConstMeta,
        argValues: [streamId, priority],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiHubHubSetPriorityConstMeta => const TaskConstMeta(
    debugName: "hub_set_priority",
    argNames: ["streamId", "priority"],
  );

  @override
  Future<List<SourceDto>> crateApiHubHubSources() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_source_dto,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiHubHubSourcesConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiHubHubSourcesConstMeta =>
      const TaskConstMeta(debugName: "hub_sources", argNames: []);

  @override
  Future<HubStatusDto> crateApiHubHubStart() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_hub_status_dto,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiHubHubStartConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiHubHubStartConstMeta =>
      const TaskConstMeta(debugName: "hub_start", argNames: []);

  @override
  Future<PairingInfoDto> crateApiHubHubStartPairing() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_pairing_info_dto,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiHubHubStartPairingConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiHubHubStartPairingConstMeta =>
      const TaskConstMeta(debugName: "hub_start_pairing", argNames: []);

  @override
  Future<HubStatusDto> crateApiHubHubStatus() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_hub_status_dto,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiHubHubStatusConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiHubHubStatusConstMeta =>
      const TaskConstMeta(debugName: "hub_status", argNames: []);

  @override
  Future<void> crateApiHubHubStop() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiHubHubStopConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiHubHubStopConstMeta =>
      const TaskConstMeta(debugName: "hub_stop", argNames: []);

  @override
  Future<AppInfo> crateApiAppInitApp({
    required String dataDir,
    String? deviceName,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(dataDir, serializer);
          sse_encode_opt_String(deviceName, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 16,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_app_info,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiAppInitAppConstMeta,
        argValues: [dataDir, deviceName],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAppInitAppConstMeta => const TaskConstMeta(
    debugName: "init_app",
    argNames: ["dataDir", "deviceName"],
  );

  @override
  Future<void> crateApiAppInitBridge() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 17,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiAppInitBridgeConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAppInitBridgeConstMeta =>
      const TaskConstMeta(debugName: "init_bridge", argNames: []);

  @override
  Future<List<CaptureAppDto>> crateApiSenderListCaptureApps() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 18,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_capture_app_dto,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSenderListCaptureAppsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSenderListCaptureAppsConstMeta =>
      const TaskConstMeta(debugName: "list_capture_apps", argNames: []);

  @override
  Future<List<String>> crateApiAppListOutputDevices() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 19,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiAppListOutputDevicesConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAppListOutputDevicesConstMeta =>
      const TaskConstMeta(debugName: "list_output_devices", argNames: []);

  @override
  Future<PairingUriDto> crateApiAppParsePairingUri({required String uri}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(uri, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 20,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_pairing_uri_dto,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiAppParsePairingUriConstMeta,
        argValues: [uri],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAppParsePairingUriConstMeta =>
      const TaskConstMeta(debugName: "parse_pairing_uri", argNames: ["uri"]);

  @override
  Stream<SenderStatusDto> crateApiSenderSenderEvents() {
    final sink = RustStreamSink<SenderStatusDto>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_StreamSink_sender_status_dto_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 21,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: sse_decode_AnyhowException,
          ),
          constMeta: kCrateApiSenderSenderEventsConstMeta,
          argValues: [sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiSenderSenderEventsConstMeta =>
      const TaskConstMeta(debugName: "sender_events", argNames: ["sink"]);

  @override
  Future<void> crateApiSenderSenderStart({required SenderStartDto request}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_sender_start_dto(request, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 22,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSenderSenderStartConstMeta,
        argValues: [request],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSenderSenderStartConstMeta =>
      const TaskConstMeta(debugName: "sender_start", argNames: ["request"]);

  @override
  Future<SenderStatusDto> crateApiSenderSenderStatus() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 23,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_sender_status_dto,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSenderSenderStatusConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSenderSenderStatusConstMeta =>
      const TaskConstMeta(debugName: "sender_status", argNames: []);

  @override
  Future<void> crateApiSenderSenderStop() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 24,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSenderSenderStopConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSenderSenderStopConstMeta =>
      const TaskConstMeta(debugName: "sender_stop", argNames: []);

  @override
  Future<void> crateApiSenderStopDiscovery() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 25,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSenderStopDiscoveryConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSenderStopDiscoveryConstMeta =>
      const TaskConstMeta(debugName: "stop_discovery", argNames: []);

  @override
  Future<List<TrustedPeerDto>> crateApiAppTrustedPeers() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 26,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_trusted_peer_dto,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiAppTrustedPeersConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAppTrustedPeersConstMeta =>
      const TaskConstMeta(debugName: "trusted_peers", argNames: []);

  @override
  Future<void> crateApiAppUpdateSettings({required SettingsDto settings}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_settings_dto(settings, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 27,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiAppUpdateSettingsConstMeta,
        argValues: [settings],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAppUpdateSettingsConstMeta =>
      const TaskConstMeta(debugName: "update_settings", argNames: ["settings"]);

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  RustStreamSink<DiscoveryEventDto>
  dco_decode_StreamSink_discovery_event_dto_Sse(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  RustStreamSink<HubEventDto> dco_decode_StreamSink_hub_event_dto_Sse(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  RustStreamSink<SenderStatusDto> dco_decode_StreamSink_sender_status_dto_Sse(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  AppInfo dco_decode_app_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return AppInfo(
      deviceId: dco_decode_String(arr[0]),
      deviceName: dco_decode_String(arr[1]),
      platform: dco_decode_String(arr[2]),
      version: dco_decode_String(arr[3]),
      capabilities: dco_decode_capabilities_dto(arr[4]),
    );
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  HubInfoDto dco_decode_box_autoadd_hub_info_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_hub_info_dto(raw);
  }

  @protected
  PairingInfoDto dco_decode_box_autoadd_pairing_info_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_pairing_info_dto(raw);
  }

  @protected
  SenderStartDto dco_decode_box_autoadd_sender_start_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_sender_start_dto(raw);
  }

  @protected
  SettingsDto dco_decode_box_autoadd_settings_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_settings_dto(raw);
  }

  @protected
  SourceDto dco_decode_box_autoadd_source_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_source_dto(raw);
  }

  @protected
  CapabilitiesDto dco_decode_capabilities_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return CapabilitiesDto(
      systemMix: dco_decode_bool(arr[0]),
      perApp: dco_decode_bool(arr[1]),
      mutesLocalOutput: dco_decode_bool(arr[2]),
      externalOnly: dco_decode_bool(arr[3]),
      notes: dco_decode_String(arr[4]),
    );
  }

  @protected
  CaptureAppDto dco_decode_capture_app_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return CaptureAppDto(
      pid: dco_decode_u_32(arr[0]),
      name: dco_decode_String(arr[1]),
    );
  }

  @protected
  CaptureSourceDto dco_decode_capture_source_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return CaptureSourceDto_System();
      case 1:
        return CaptureSourceDto_SystemExcludingSelf();
      case 2:
        return CaptureSourceDto_Process(pid: dco_decode_u_32(raw[1]));
      case 3:
        return CaptureSourceDto_Tone(freqHz: dco_decode_f_32(raw[1]));
      case 4:
        return CaptureSourceDto_External(
          feedId: dco_decode_u_32(raw[1]),
          sampleRate: dco_decode_u_32(raw[2]),
          channels: dco_decode_u_16(raw[3]),
        );
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  DiscoveryEventDto dco_decode_discovery_event_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return DiscoveryEventDto_Found(
          dco_decode_box_autoadd_hub_info_dto(raw[1]),
        );
      case 1:
        return DiscoveryEventDto_Lost(deviceId: dco_decode_String(raw[1]));
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  double dco_decode_f_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  HubEventDto dco_decode_hub_event_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return HubEventDto_SourceAdded(
          dco_decode_box_autoadd_source_dto(raw[1]),
        );
      case 1:
        return HubEventDto_SourceRemoved(streamId: dco_decode_u_32(raw[1]));
      case 2:
        return HubEventDto_SourceUpdated(
          dco_decode_box_autoadd_source_dto(raw[1]),
        );
      case 3:
        return HubEventDto_PairingCompleted(
          deviceId: dco_decode_String(raw[1]),
          name: dco_decode_String(raw[2]),
        );
      case 4:
        return HubEventDto_PairingFailed(reason: dco_decode_String(raw[1]));
      case 5:
        return HubEventDto_Error(message: dco_decode_String(raw[1]));
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  HubInfoDto dco_decode_hub_info_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return HubInfoDto(
      deviceId: dco_decode_String(arr[0]),
      name: dco_decode_String(arr[1]),
      addrs: dco_decode_list_String(arr[2]),
      port: dco_decode_u_16(arr[3]),
      platform: dco_decode_String(arr[4]),
      trusted: dco_decode_bool(arr[5]),
    );
  }

  @protected
  HubStatusDto dco_decode_hub_status_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return HubStatusDto(
      running: dco_decode_bool(arr[0]),
      port: dco_decode_u_16(arr[1]),
      deviceName: dco_decode_String(arr[2]),
      sourceCount: dco_decode_u_32(arr[3]),
      advertised: dco_decode_bool(arr[4]),
      advertiseError: dco_decode_opt_String(arr[5]),
    );
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<CaptureAppDto> dco_decode_list_capture_app_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_capture_app_dto).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<SourceDto> dco_decode_list_source_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_source_dto).toList();
  }

  @protected
  List<TrustedPeerDto> dco_decode_list_trusted_peer_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_trusted_peer_dto).toList();
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  PairingInfoDto? dco_decode_opt_box_autoadd_pairing_info_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_pairing_info_dto(raw);
  }

  @protected
  PairingInfoDto dco_decode_pairing_info_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return PairingInfoDto(
      pin: dco_decode_String(arr[0]),
      token: dco_decode_String(arr[1]),
      uri: dco_decode_String(arr[2]),
      expiresAtUnix: dco_decode_i_64(arr[3]),
    );
  }

  @protected
  PairingUriDto dco_decode_pairing_uri_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return PairingUriDto(
      host: dco_decode_String(arr[0]),
      port: dco_decode_u_16(arr[1]),
      hubId: dco_decode_String(arr[2]),
      hubDeviceId: dco_decode_String(arr[3]),
      token: dco_decode_String(arr[4]),
      name: dco_decode_String(arr[5]),
    );
  }

  @protected
  SenderStartDto dco_decode_sender_start_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return SenderStartDto(
      hubHost: dco_decode_String(arr[0]),
      hubPort: dco_decode_u_16(arr[1]),
      hubDeviceId: dco_decode_opt_String(arr[2]),
      hubKey: dco_decode_opt_String(arr[3]),
      pairingSecret: dco_decode_opt_String(arr[4]),
      source: dco_decode_capture_source_dto(arr[5]),
      label: dco_decode_String(arr[6]),
    );
  }

  @protected
  SenderStatusDto dco_decode_sender_status_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 10)
      throw Exception('unexpected arr length: expect 10 but see ${arr.length}');
    return SenderStatusDto(
      state: dco_decode_String(arr[0]),
      error: dco_decode_opt_String(arr[1]),
      hubName: dco_decode_opt_String(arr[2]),
      bitrate: dco_decode_u_32(arr[3]),
      lossPct: dco_decode_f_32(arr[4]),
      rttMs: dco_decode_f_32(arr[5]),
      levelDb: dco_decode_f_32(arr[6]),
      hubGain: dco_decode_f_32(arr[7]),
      hubMuted: dco_decode_bool(arr[8]),
      hubPriority: dco_decode_bool(arr[9]),
    );
  }

  @protected
  SettingsDto dco_decode_settings_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 8)
      throw Exception('unexpected arr length: expect 8 but see ${arr.length}');
    return SettingsDto(
      deviceName: dco_decode_String(arr[0]),
      port: dco_decode_u_16(arr[1]),
      bitrate: dco_decode_u_32(arr[2]),
      frameMs: dco_decode_u_8(arr[3]),
      fec: dco_decode_bool(arr[4]),
      jitterMinMs: dco_decode_u_32(arr[5]),
      jitterMaxMs: dco_decode_u_32(arr[6]),
      outputDevice: dco_decode_opt_String(arr[7]),
    );
  }

  @protected
  SourceDto dco_decode_source_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 14)
      throw Exception('unexpected arr length: expect 14 but see ${arr.length}');
    return SourceDto(
      streamId: dco_decode_u_32(arr[0]),
      deviceId: dco_decode_String(arr[1]),
      deviceName: dco_decode_String(arr[2]),
      label: dco_decode_String(arr[3]),
      platform: dco_decode_String(arr[4]),
      gain: dco_decode_f_32(arr[5]),
      muted: dco_decode_bool(arr[6]),
      priority: dco_decode_bool(arr[7]),
      active: dco_decode_bool(arr[8]),
      lossPct: dco_decode_f_32(arr[9]),
      jitterMs: dco_decode_f_32(arr[10]),
      bufferMs: dco_decode_f_32(arr[11]),
      latencyMs: dco_decode_f_32(arr[12]),
      levelDb: dco_decode_f_32(arr[13]),
    );
  }

  @protected
  TrustedPeerDto dco_decode_trusted_peer_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return TrustedPeerDto(
      deviceId: dco_decode_String(arr[0]),
      name: dco_decode_String(arr[1]),
      pairedAtUnix: dco_decode_i_64(arr[2]),
    );
  }

  @protected
  int dco_decode_u_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  RustStreamSink<DiscoveryEventDto>
  sse_decode_StreamSink_discovery_event_dto_Sse(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  RustStreamSink<HubEventDto> sse_decode_StreamSink_hub_event_dto_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  RustStreamSink<SenderStatusDto> sse_decode_StreamSink_sender_status_dto_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  AppInfo sse_decode_app_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_deviceId = sse_decode_String(deserializer);
    var var_deviceName = sse_decode_String(deserializer);
    var var_platform = sse_decode_String(deserializer);
    var var_version = sse_decode_String(deserializer);
    var var_capabilities = sse_decode_capabilities_dto(deserializer);
    return AppInfo(
      deviceId: var_deviceId,
      deviceName: var_deviceName,
      platform: var_platform,
      version: var_version,
      capabilities: var_capabilities,
    );
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  HubInfoDto sse_decode_box_autoadd_hub_info_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_hub_info_dto(deserializer));
  }

  @protected
  PairingInfoDto sse_decode_box_autoadd_pairing_info_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_pairing_info_dto(deserializer));
  }

  @protected
  SenderStartDto sse_decode_box_autoadd_sender_start_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_sender_start_dto(deserializer));
  }

  @protected
  SettingsDto sse_decode_box_autoadd_settings_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_settings_dto(deserializer));
  }

  @protected
  SourceDto sse_decode_box_autoadd_source_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_source_dto(deserializer));
  }

  @protected
  CapabilitiesDto sse_decode_capabilities_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_systemMix = sse_decode_bool(deserializer);
    var var_perApp = sse_decode_bool(deserializer);
    var var_mutesLocalOutput = sse_decode_bool(deserializer);
    var var_externalOnly = sse_decode_bool(deserializer);
    var var_notes = sse_decode_String(deserializer);
    return CapabilitiesDto(
      systemMix: var_systemMix,
      perApp: var_perApp,
      mutesLocalOutput: var_mutesLocalOutput,
      externalOnly: var_externalOnly,
      notes: var_notes,
    );
  }

  @protected
  CaptureAppDto sse_decode_capture_app_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_pid = sse_decode_u_32(deserializer);
    var var_name = sse_decode_String(deserializer);
    return CaptureAppDto(pid: var_pid, name: var_name);
  }

  @protected
  CaptureSourceDto sse_decode_capture_source_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        return CaptureSourceDto_System();
      case 1:
        return CaptureSourceDto_SystemExcludingSelf();
      case 2:
        var var_pid = sse_decode_u_32(deserializer);
        return CaptureSourceDto_Process(pid: var_pid);
      case 3:
        var var_freqHz = sse_decode_f_32(deserializer);
        return CaptureSourceDto_Tone(freqHz: var_freqHz);
      case 4:
        var var_feedId = sse_decode_u_32(deserializer);
        var var_sampleRate = sse_decode_u_32(deserializer);
        var var_channels = sse_decode_u_16(deserializer);
        return CaptureSourceDto_External(
          feedId: var_feedId,
          sampleRate: var_sampleRate,
          channels: var_channels,
        );
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  DiscoveryEventDto sse_decode_discovery_event_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        var var_field0 = sse_decode_box_autoadd_hub_info_dto(deserializer);
        return DiscoveryEventDto_Found(var_field0);
      case 1:
        var var_deviceId = sse_decode_String(deserializer);
        return DiscoveryEventDto_Lost(deviceId: var_deviceId);
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  double sse_decode_f_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat32();
  }

  @protected
  HubEventDto sse_decode_hub_event_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        var var_field0 = sse_decode_box_autoadd_source_dto(deserializer);
        return HubEventDto_SourceAdded(var_field0);
      case 1:
        var var_streamId = sse_decode_u_32(deserializer);
        return HubEventDto_SourceRemoved(streamId: var_streamId);
      case 2:
        var var_field0 = sse_decode_box_autoadd_source_dto(deserializer);
        return HubEventDto_SourceUpdated(var_field0);
      case 3:
        var var_deviceId = sse_decode_String(deserializer);
        var var_name = sse_decode_String(deserializer);
        return HubEventDto_PairingCompleted(
          deviceId: var_deviceId,
          name: var_name,
        );
      case 4:
        var var_reason = sse_decode_String(deserializer);
        return HubEventDto_PairingFailed(reason: var_reason);
      case 5:
        var var_message = sse_decode_String(deserializer);
        return HubEventDto_Error(message: var_message);
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  HubInfoDto sse_decode_hub_info_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_deviceId = sse_decode_String(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_addrs = sse_decode_list_String(deserializer);
    var var_port = sse_decode_u_16(deserializer);
    var var_platform = sse_decode_String(deserializer);
    var var_trusted = sse_decode_bool(deserializer);
    return HubInfoDto(
      deviceId: var_deviceId,
      name: var_name,
      addrs: var_addrs,
      port: var_port,
      platform: var_platform,
      trusted: var_trusted,
    );
  }

  @protected
  HubStatusDto sse_decode_hub_status_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_running = sse_decode_bool(deserializer);
    var var_port = sse_decode_u_16(deserializer);
    var var_deviceName = sse_decode_String(deserializer);
    var var_sourceCount = sse_decode_u_32(deserializer);
    var var_advertised = sse_decode_bool(deserializer);
    var var_advertiseError = sse_decode_opt_String(deserializer);
    return HubStatusDto(
      running: var_running,
      port: var_port,
      deviceName: var_deviceName,
      sourceCount: var_sourceCount,
      advertised: var_advertised,
      advertiseError: var_advertiseError,
    );
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<CaptureAppDto> sse_decode_list_capture_app_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <CaptureAppDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_capture_app_dto(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<SourceDto> sse_decode_list_source_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <SourceDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_source_dto(deserializer));
    }
    return ans_;
  }

  @protected
  List<TrustedPeerDto> sse_decode_list_trusted_peer_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <TrustedPeerDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_trusted_peer_dto(deserializer));
    }
    return ans_;
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PairingInfoDto? sse_decode_opt_box_autoadd_pairing_info_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_pairing_info_dto(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PairingInfoDto sse_decode_pairing_info_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_pin = sse_decode_String(deserializer);
    var var_token = sse_decode_String(deserializer);
    var var_uri = sse_decode_String(deserializer);
    var var_expiresAtUnix = sse_decode_i_64(deserializer);
    return PairingInfoDto(
      pin: var_pin,
      token: var_token,
      uri: var_uri,
      expiresAtUnix: var_expiresAtUnix,
    );
  }

  @protected
  PairingUriDto sse_decode_pairing_uri_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_host = sse_decode_String(deserializer);
    var var_port = sse_decode_u_16(deserializer);
    var var_hubId = sse_decode_String(deserializer);
    var var_hubDeviceId = sse_decode_String(deserializer);
    var var_token = sse_decode_String(deserializer);
    var var_name = sse_decode_String(deserializer);
    return PairingUriDto(
      host: var_host,
      port: var_port,
      hubId: var_hubId,
      hubDeviceId: var_hubDeviceId,
      token: var_token,
      name: var_name,
    );
  }

  @protected
  SenderStartDto sse_decode_sender_start_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_hubHost = sse_decode_String(deserializer);
    var var_hubPort = sse_decode_u_16(deserializer);
    var var_hubDeviceId = sse_decode_opt_String(deserializer);
    var var_hubKey = sse_decode_opt_String(deserializer);
    var var_pairingSecret = sse_decode_opt_String(deserializer);
    var var_source = sse_decode_capture_source_dto(deserializer);
    var var_label = sse_decode_String(deserializer);
    return SenderStartDto(
      hubHost: var_hubHost,
      hubPort: var_hubPort,
      hubDeviceId: var_hubDeviceId,
      hubKey: var_hubKey,
      pairingSecret: var_pairingSecret,
      source: var_source,
      label: var_label,
    );
  }

  @protected
  SenderStatusDto sse_decode_sender_status_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_state = sse_decode_String(deserializer);
    var var_error = sse_decode_opt_String(deserializer);
    var var_hubName = sse_decode_opt_String(deserializer);
    var var_bitrate = sse_decode_u_32(deserializer);
    var var_lossPct = sse_decode_f_32(deserializer);
    var var_rttMs = sse_decode_f_32(deserializer);
    var var_levelDb = sse_decode_f_32(deserializer);
    var var_hubGain = sse_decode_f_32(deserializer);
    var var_hubMuted = sse_decode_bool(deserializer);
    var var_hubPriority = sse_decode_bool(deserializer);
    return SenderStatusDto(
      state: var_state,
      error: var_error,
      hubName: var_hubName,
      bitrate: var_bitrate,
      lossPct: var_lossPct,
      rttMs: var_rttMs,
      levelDb: var_levelDb,
      hubGain: var_hubGain,
      hubMuted: var_hubMuted,
      hubPriority: var_hubPriority,
    );
  }

  @protected
  SettingsDto sse_decode_settings_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_deviceName = sse_decode_String(deserializer);
    var var_port = sse_decode_u_16(deserializer);
    var var_bitrate = sse_decode_u_32(deserializer);
    var var_frameMs = sse_decode_u_8(deserializer);
    var var_fec = sse_decode_bool(deserializer);
    var var_jitterMinMs = sse_decode_u_32(deserializer);
    var var_jitterMaxMs = sse_decode_u_32(deserializer);
    var var_outputDevice = sse_decode_opt_String(deserializer);
    return SettingsDto(
      deviceName: var_deviceName,
      port: var_port,
      bitrate: var_bitrate,
      frameMs: var_frameMs,
      fec: var_fec,
      jitterMinMs: var_jitterMinMs,
      jitterMaxMs: var_jitterMaxMs,
      outputDevice: var_outputDevice,
    );
  }

  @protected
  SourceDto sse_decode_source_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_streamId = sse_decode_u_32(deserializer);
    var var_deviceId = sse_decode_String(deserializer);
    var var_deviceName = sse_decode_String(deserializer);
    var var_label = sse_decode_String(deserializer);
    var var_platform = sse_decode_String(deserializer);
    var var_gain = sse_decode_f_32(deserializer);
    var var_muted = sse_decode_bool(deserializer);
    var var_priority = sse_decode_bool(deserializer);
    var var_active = sse_decode_bool(deserializer);
    var var_lossPct = sse_decode_f_32(deserializer);
    var var_jitterMs = sse_decode_f_32(deserializer);
    var var_bufferMs = sse_decode_f_32(deserializer);
    var var_latencyMs = sse_decode_f_32(deserializer);
    var var_levelDb = sse_decode_f_32(deserializer);
    return SourceDto(
      streamId: var_streamId,
      deviceId: var_deviceId,
      deviceName: var_deviceName,
      label: var_label,
      platform: var_platform,
      gain: var_gain,
      muted: var_muted,
      priority: var_priority,
      active: var_active,
      lossPct: var_lossPct,
      jitterMs: var_jitterMs,
      bufferMs: var_bufferMs,
      latencyMs: var_latencyMs,
      levelDb: var_levelDb,
    );
  }

  @protected
  TrustedPeerDto sse_decode_trusted_peer_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_deviceId = sse_decode_String(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_pairedAtUnix = sse_decode_i_64(deserializer);
    return TrustedPeerDto(
      deviceId: var_deviceId,
      name: var_name,
      pairedAtUnix: var_pairedAtUnix,
    );
  }

  @protected
  int sse_decode_u_16(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint16();
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_StreamSink_discovery_event_dto_Sse(
    RustStreamSink<DiscoveryEventDto> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_discovery_event_dto,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_StreamSink_hub_event_dto_Sse(
    RustStreamSink<HubEventDto> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_hub_event_dto,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_StreamSink_sender_status_dto_Sse(
    RustStreamSink<SenderStatusDto> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_sender_status_dto,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_app_info(AppInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.deviceId, serializer);
    sse_encode_String(self.deviceName, serializer);
    sse_encode_String(self.platform, serializer);
    sse_encode_String(self.version, serializer);
    sse_encode_capabilities_dto(self.capabilities, serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_hub_info_dto(
    HubInfoDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_hub_info_dto(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_pairing_info_dto(
    PairingInfoDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_pairing_info_dto(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_sender_start_dto(
    SenderStartDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_sender_start_dto(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_settings_dto(
    SettingsDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_settings_dto(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_source_dto(
    SourceDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_source_dto(self, serializer);
  }

  @protected
  void sse_encode_capabilities_dto(
    CapabilitiesDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.systemMix, serializer);
    sse_encode_bool(self.perApp, serializer);
    sse_encode_bool(self.mutesLocalOutput, serializer);
    sse_encode_bool(self.externalOnly, serializer);
    sse_encode_String(self.notes, serializer);
  }

  @protected
  void sse_encode_capture_app_dto(
    CaptureAppDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.pid, serializer);
    sse_encode_String(self.name, serializer);
  }

  @protected
  void sse_encode_capture_source_dto(
    CaptureSourceDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case CaptureSourceDto_System():
        sse_encode_i_32(0, serializer);
      case CaptureSourceDto_SystemExcludingSelf():
        sse_encode_i_32(1, serializer);
      case CaptureSourceDto_Process(pid: final pid):
        sse_encode_i_32(2, serializer);
        sse_encode_u_32(pid, serializer);
      case CaptureSourceDto_Tone(freqHz: final freqHz):
        sse_encode_i_32(3, serializer);
        sse_encode_f_32(freqHz, serializer);
      case CaptureSourceDto_External(
        feedId: final feedId,
        sampleRate: final sampleRate,
        channels: final channels,
      ):
        sse_encode_i_32(4, serializer);
        sse_encode_u_32(feedId, serializer);
        sse_encode_u_32(sampleRate, serializer);
        sse_encode_u_16(channels, serializer);
    }
  }

  @protected
  void sse_encode_discovery_event_dto(
    DiscoveryEventDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case DiscoveryEventDto_Found(field0: final field0):
        sse_encode_i_32(0, serializer);
        sse_encode_box_autoadd_hub_info_dto(field0, serializer);
      case DiscoveryEventDto_Lost(deviceId: final deviceId):
        sse_encode_i_32(1, serializer);
        sse_encode_String(deviceId, serializer);
    }
  }

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat32(self);
  }

  @protected
  void sse_encode_hub_event_dto(HubEventDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case HubEventDto_SourceAdded(field0: final field0):
        sse_encode_i_32(0, serializer);
        sse_encode_box_autoadd_source_dto(field0, serializer);
      case HubEventDto_SourceRemoved(streamId: final streamId):
        sse_encode_i_32(1, serializer);
        sse_encode_u_32(streamId, serializer);
      case HubEventDto_SourceUpdated(field0: final field0):
        sse_encode_i_32(2, serializer);
        sse_encode_box_autoadd_source_dto(field0, serializer);
      case HubEventDto_PairingCompleted(
        deviceId: final deviceId,
        name: final name,
      ):
        sse_encode_i_32(3, serializer);
        sse_encode_String(deviceId, serializer);
        sse_encode_String(name, serializer);
      case HubEventDto_PairingFailed(reason: final reason):
        sse_encode_i_32(4, serializer);
        sse_encode_String(reason, serializer);
      case HubEventDto_Error(message: final message):
        sse_encode_i_32(5, serializer);
        sse_encode_String(message, serializer);
    }
  }

  @protected
  void sse_encode_hub_info_dto(HubInfoDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.deviceId, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_list_String(self.addrs, serializer);
    sse_encode_u_16(self.port, serializer);
    sse_encode_String(self.platform, serializer);
    sse_encode_bool(self.trusted, serializer);
  }

  @protected
  void sse_encode_hub_status_dto(HubStatusDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.running, serializer);
    sse_encode_u_16(self.port, serializer);
    sse_encode_String(self.deviceName, serializer);
    sse_encode_u_32(self.sourceCount, serializer);
    sse_encode_bool(self.advertised, serializer);
    sse_encode_opt_String(self.advertiseError, serializer);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_capture_app_dto(
    List<CaptureAppDto> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_capture_app_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_source_dto(
    List<SourceDto> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_source_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_list_trusted_peer_dto(
    List<TrustedPeerDto> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_trusted_peer_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_pairing_info_dto(
    PairingInfoDto? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_pairing_info_dto(self, serializer);
    }
  }

  @protected
  void sse_encode_pairing_info_dto(
    PairingInfoDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.pin, serializer);
    sse_encode_String(self.token, serializer);
    sse_encode_String(self.uri, serializer);
    sse_encode_i_64(self.expiresAtUnix, serializer);
  }

  @protected
  void sse_encode_pairing_uri_dto(
    PairingUriDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.host, serializer);
    sse_encode_u_16(self.port, serializer);
    sse_encode_String(self.hubId, serializer);
    sse_encode_String(self.hubDeviceId, serializer);
    sse_encode_String(self.token, serializer);
    sse_encode_String(self.name, serializer);
  }

  @protected
  void sse_encode_sender_start_dto(
    SenderStartDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.hubHost, serializer);
    sse_encode_u_16(self.hubPort, serializer);
    sse_encode_opt_String(self.hubDeviceId, serializer);
    sse_encode_opt_String(self.hubKey, serializer);
    sse_encode_opt_String(self.pairingSecret, serializer);
    sse_encode_capture_source_dto(self.source, serializer);
    sse_encode_String(self.label, serializer);
  }

  @protected
  void sse_encode_sender_status_dto(
    SenderStatusDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.state, serializer);
    sse_encode_opt_String(self.error, serializer);
    sse_encode_opt_String(self.hubName, serializer);
    sse_encode_u_32(self.bitrate, serializer);
    sse_encode_f_32(self.lossPct, serializer);
    sse_encode_f_32(self.rttMs, serializer);
    sse_encode_f_32(self.levelDb, serializer);
    sse_encode_f_32(self.hubGain, serializer);
    sse_encode_bool(self.hubMuted, serializer);
    sse_encode_bool(self.hubPriority, serializer);
  }

  @protected
  void sse_encode_settings_dto(SettingsDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.deviceName, serializer);
    sse_encode_u_16(self.port, serializer);
    sse_encode_u_32(self.bitrate, serializer);
    sse_encode_u_8(self.frameMs, serializer);
    sse_encode_bool(self.fec, serializer);
    sse_encode_u_32(self.jitterMinMs, serializer);
    sse_encode_u_32(self.jitterMaxMs, serializer);
    sse_encode_opt_String(self.outputDevice, serializer);
  }

  @protected
  void sse_encode_source_dto(SourceDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.streamId, serializer);
    sse_encode_String(self.deviceId, serializer);
    sse_encode_String(self.deviceName, serializer);
    sse_encode_String(self.label, serializer);
    sse_encode_String(self.platform, serializer);
    sse_encode_f_32(self.gain, serializer);
    sse_encode_bool(self.muted, serializer);
    sse_encode_bool(self.priority, serializer);
    sse_encode_bool(self.active, serializer);
    sse_encode_f_32(self.lossPct, serializer);
    sse_encode_f_32(self.jitterMs, serializer);
    sse_encode_f_32(self.bufferMs, serializer);
    sse_encode_f_32(self.latencyMs, serializer);
    sse_encode_f_32(self.levelDb, serializer);
  }

  @protected
  void sse_encode_trusted_peer_dto(
    TrustedPeerDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.deviceId, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_i_64(self.pairedAtUnix, serializer);
  }

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint16(self);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}
