// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

/// Loads (or creates) settings, identity and trust store in `data_dir` and sets up logging.
///
/// `device_name` is the name to use **on first run** (no `settings.json` yet), e.g. the
/// device model on mobile where the OS host name is useless; afterwards the saved name wins
/// (change it with `update_settings`). Idempotent: calling it again with the same
/// `data_dir` returns the current info; another `data_dir` is only accepted while neither a
/// hub nor a sender runs.
Future<AppInfo> initApp({required String dataDir, String? deviceName}) =>
    RustLib.instance.api.crateApiAppInitApp(
      dataDir: dataDir,
      deviceName: deviceName,
    );

/// The current settings.
Future<SettingsDto> getSettings() =>
    RustLib.instance.api.crateApiAppGetSettings();

/// Validates, saves and applies settings. A running hub or sender keeps its settings until it
/// is restarted.
Future<void> updateSettings({required SettingsDto settings}) =>
    RustLib.instance.api.crateApiAppUpdateSettings(settings: settings);

/// Names of the available output devices (for `SettingsDto.output_device`).
Future<List<String>> listOutputDevices() =>
    RustLib.instance.api.crateApiAppListOutputDevices();

/// The paired devices.
Future<List<TrustedPeerDto>> trustedPeers() =>
    RustLib.instance.api.crateApiAppTrustedPeers();

/// Removes a paired device (no-op for an unknown id). A running hub or sender keeps its own
/// copy of the trust store until it is restarted.
Future<void> forgetPeer({required String deviceId}) =>
    RustLib.instance.api.crateApiAppForgetPeer(deviceId: deviceId);

/// Parses a pairing URI scanned from a QR code.
Future<PairingUriDto> parsePairingUri({required String uri}) =>
    RustLib.instance.api.crateApiAppParsePairingUri(uri: uri);

/// What the app shows about this device.
class AppInfo {
  /// Fingerprint of this device's static key (`ab12-cd34-ef56-7890`).
  final String deviceId;

  /// Name shown to other devices.
  final String deviceName;

  /// `windows`, `macos`, `linux`, `android`, `ios` or `unknown`.
  final String platform;

  /// App (crate) version.
  final String version;

  /// What capture can do here.
  final CapabilitiesDto capabilities;

  const AppInfo({
    required this.deviceId,
    required this.deviceName,
    required this.platform,
    required this.version,
    required this.capabilities,
  });

  @override
  int get hashCode =>
      deviceId.hashCode ^
      deviceName.hashCode ^
      platform.hashCode ^
      version.hashCode ^
      capabilities.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AppInfo &&
          runtimeType == other.runtimeType &&
          deviceId == other.deviceId &&
          deviceName == other.deviceName &&
          platform == other.platform &&
          version == other.version &&
          capabilities == other.capabilities;
}

/// Capture capabilities of this platform.
class CapabilitiesDto {
  /// Rust can capture the system mix (`CaptureSourceDto::System` / `SystemExcludingSelf`).
  final bool systemMix;

  /// Rust can capture single processes (`CaptureSourceDto::Process`, `list_capture_apps`).
  final bool perApp;

  /// Capturing silences the local speakers (macOS process taps).
  final bool mutesLocalOutput;

  /// Capture only works through native code pushing into an external feed (Android
  /// `CaptureService`, iOS broadcast extension): use `CaptureSourceDto::External`.
  final bool externalOnly;

  /// Human-readable caveats.
  final String notes;

  const CapabilitiesDto({
    required this.systemMix,
    required this.perApp,
    required this.mutesLocalOutput,
    required this.externalOnly,
    required this.notes,
  });

  @override
  int get hashCode =>
      systemMix.hashCode ^
      perApp.hashCode ^
      mutesLocalOutput.hashCode ^
      externalOnly.hashCode ^
      notes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CapabilitiesDto &&
          runtimeType == other.runtimeType &&
          systemMix == other.systemMix &&
          perApp == other.perApp &&
          mutesLocalOutput == other.mutesLocalOutput &&
          externalOnly == other.externalOnly &&
          notes == other.notes;
}

/// A parsed `hfa://pair?...` URI (from a QR code).
class PairingUriDto {
  /// Hub host (IPv6 without brackets).
  final String host;

  /// Hub port.
  final int port;

  /// Hub static key, unpadded base64url: pass it as `SenderStartDto.hub_key`.
  final String hubId;

  /// Hub device id (fingerprint of `hub_id`).
  final String hubDeviceId;

  /// One-time pairing token: pass it as `SenderStartDto.pairing_secret`.
  final String token;

  /// Hub display name.
  final String name;

  const PairingUriDto({
    required this.host,
    required this.port,
    required this.hubId,
    required this.hubDeviceId,
    required this.token,
    required this.name,
  });

  @override
  int get hashCode =>
      host.hashCode ^
      port.hashCode ^
      hubId.hashCode ^
      hubDeviceId.hashCode ^
      token.hashCode ^
      name.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PairingUriDto &&
          runtimeType == other.runtimeType &&
          host == other.host &&
          port == other.port &&
          hubId == other.hubId &&
          hubDeviceId == other.hubDeviceId &&
          token == other.token &&
          name == other.name;
}

/// Editable settings.
class SettingsDto {
  /// Name shown to other devices (1..=64 characters, no control characters).
  final String deviceName;

  /// Hub TCP/UDP port (0 = any free port) and default port for senders.
  final int port;

  /// Initial Opus bitrate, 6000..=510000 bit/s.
  final int bitrate;

  /// Opus frame length: 10 or 20 ms.
  final int frameMs;

  /// Opus in-band FEC.
  final bool fec;

  /// Minimum jitter-buffer target (ms), 1..=`jitter_max_ms`.
  final int jitterMinMs;

  /// Maximum jitter-buffer target (ms), at most 2000.
  final int jitterMaxMs;

  /// Hub output device name (`list_output_devices`); `None` = the OS default output.
  final String? outputDevice;

  const SettingsDto({
    required this.deviceName,
    required this.port,
    required this.bitrate,
    required this.frameMs,
    required this.fec,
    required this.jitterMinMs,
    required this.jitterMaxMs,
    this.outputDevice,
  });

  @override
  int get hashCode =>
      deviceName.hashCode ^
      port.hashCode ^
      bitrate.hashCode ^
      frameMs.hashCode ^
      fec.hashCode ^
      jitterMinMs.hashCode ^
      jitterMaxMs.hashCode ^
      outputDevice.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SettingsDto &&
          runtimeType == other.runtimeType &&
          deviceName == other.deviceName &&
          port == other.port &&
          bitrate == other.bitrate &&
          frameMs == other.frameMs &&
          fec == other.fec &&
          jitterMinMs == other.jitterMinMs &&
          jitterMaxMs == other.jitterMaxMs &&
          outputDevice == other.outputDevice;
}

/// A paired device.
class TrustedPeerDto {
  /// Device id (fingerprint).
  final String deviceId;

  /// Name at pairing time.
  final String name;

  /// Unix time (seconds) of pairing.
  final PlatformInt64 pairedAtUnix;

  const TrustedPeerDto({
    required this.deviceId,
    required this.name,
    required this.pairedAtUnix,
  });

  @override
  int get hashCode => deviceId.hashCode ^ name.hashCode ^ pairedAtUnix.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TrustedPeerDto &&
          runtimeType == other.runtimeType &&
          deviceId == other.deviceId &&
          name == other.name &&
          pairedAtUnix == other.pairedAtUnix;
}
