// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'hub.freezed.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`

/// Starts the hub (output from the settings, mDNS advertising on). Idempotent: returns the
/// status of the running hub. A failure to advertise does not fail the start: it shows in
/// `HubStatusDto.advertised` / `advertise_error` and as a `HubEventDto::Error`.
Future<HubStatusDto> hubStart() => RustLib.instance.api.crateApiHubHubStart();

/// Stops the hub (no-op if it is not running).
Future<void> hubStop() => RustLib.instance.api.crateApiHubHubStop();

/// Current hub status (`running: false` when stopped).
Future<HubStatusDto> hubStatus() => RustLib.instance.api.crateApiHubHubStatus();

/// Current streams (empty when the hub is stopped).
Future<List<SourceDto>> hubSources() =>
    RustLib.instance.api.crateApiHubHubSources();

/// Sets a stream's linear gain (0.0..=4.0).
Future<void> hubSetGain({required int streamId, required double gain}) =>
    RustLib.instance.api.crateApiHubHubSetGain(streamId: streamId, gain: gain);

/// Mutes or unmutes a stream.
Future<void> hubSetMuted({required int streamId, required bool muted}) =>
    RustLib.instance.api.crateApiHubHubSetMuted(
      streamId: streamId,
      muted: muted,
    );

/// Marks a stream as priority (it ducks the others while it plays).
Future<void> hubSetPriority({required int streamId, required bool priority}) =>
    RustLib.instance.api.crateApiHubHubSetPriority(
      streamId: streamId,
      priority: priority,
    );

/// Sets and saves the master linear gain (0.0..=4.0): applied at once while the hub runs,
/// and by every later hub start (it survives hub and app restarts). Allowed while the hub is
/// stopped.
Future<void> hubSetMasterGain({required double gain}) =>
    RustLib.instance.api.crateApiHubHubSetMasterGain(gain: gain);

/// Opens a pairing window (5 minutes, one-time PIN and token).
Future<PairingInfoDto> hubStartPairing() =>
    RustLib.instance.api.crateApiHubHubStartPairing();

/// The open pairing window, or `None`: none was opened, it was cancelled, it expired, a
/// sender paired, or the hub closed it after 5 failed attempts (a `PairingFailed` event does
/// not say which). `None` while the hub is stopped.
Future<PairingInfoDto?> hubPairingStatus() =>
    RustLib.instance.api.crateApiHubHubPairingStatus();

/// Closes the pairing window.
Future<void> hubCancelPairing() =>
    RustLib.instance.api.crateApiHubHubCancelPairing();

/// Subscribes to hub events. The subscription lives until the Dart stream is cancelled and
/// survives hub restarts (events flow while a hub runs).
Stream<HubEventDto> hubEvents() => RustLib.instance.api.crateApiHubHubEvents();

@freezed
sealed class HubEventDto with _$HubEventDto {
  const HubEventDto._();

  /// A stream started.
  const factory HubEventDto.sourceAdded(SourceDto field0) =
      HubEventDto_SourceAdded;

  /// A stream stopped or timed out.
  const factory HubEventDto.sourceRemoved({
    /// The removed stream.
    required int streamId,
  }) = HubEventDto_SourceRemoved;

  /// Controls, activity or statistics of a stream changed (about once per second).
  const factory HubEventDto.sourceUpdated(SourceDto field0) =
      HubEventDto_SourceUpdated;

  /// A sender paired.
  const factory HubEventDto.pairingCompleted({
    /// Sender device id.
    required String deviceId,

    /// Sender name.
    required String name,
  }) = HubEventDto_PairingCompleted;

  /// A pairing attempt failed.
  const factory HubEventDto.pairingFailed({
    /// Human-readable reason.
    required String reason,
  }) = HubEventDto_PairingFailed;

  /// A non-fatal error.
  const factory HubEventDto.error({
    /// Human-readable message.
    required String message,
  }) = HubEventDto_Error;
}

/// Hub state for the UI.
class HubStatusDto {
  /// The hub is running.
  final bool running;

  /// Bound TCP/UDP port (0 when not running).
  final int port;

  /// This device's name as shown to senders.
  final String deviceName;

  /// Number of current streams.
  final int sourceCount;

  /// The hub is announced over mDNS, so senders on the network can find it. `false` while
  /// stopped, or when advertising failed (see `advertise_error`): senders must then enter
  /// the hub's address.
  final bool advertised;

  /// Why advertising failed (e.g. no multicast on iOS without the entitlement), if it did.
  final String? advertiseError;

  /// The master linear gain (0.0..=4.0): the saved value (`hub_set_master_gain`), which a
  /// starting hub applies. Also reported while stopped.
  final double masterGain;

  /// Where senders can reach the hub, to type into "Add by address": `ip:port` for each
  /// LAN address, IPv4 first, then IPv6 as `[addr]:port` (see
  /// `hfa_core::pairing::lan_addresses`). Empty while stopped or without a network.
  final List<String> addresses;

  const HubStatusDto({
    required this.running,
    required this.port,
    required this.deviceName,
    required this.sourceCount,
    required this.advertised,
    this.advertiseError,
    required this.masterGain,
    required this.addresses,
  });

  @override
  int get hashCode =>
      running.hashCode ^
      port.hashCode ^
      deviceName.hashCode ^
      sourceCount.hashCode ^
      advertised.hashCode ^
      advertiseError.hashCode ^
      masterGain.hashCode ^
      addresses.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HubStatusDto &&
          runtimeType == other.runtimeType &&
          running == other.running &&
          port == other.port &&
          deviceName == other.deviceName &&
          sourceCount == other.sourceCount &&
          advertised == other.advertised &&
          advertiseError == other.advertiseError &&
          masterGain == other.masterGain &&
          addresses == other.addresses;
}

/// An open pairing window. Show `pin` and a QR code of `uri`.
class PairingInfoDto {
  /// 6-digit PIN.
  final String pin;

  /// One-time token (also inside `uri`).
  final String token;

  /// `hfa://pair?...` URI for the QR code.
  final String uri;

  /// Unix time (seconds) when the window closes.
  final PlatformInt64 expiresAtUnix;

  const PairingInfoDto({
    required this.pin,
    required this.token,
    required this.uri,
    required this.expiresAtUnix,
  });

  @override
  int get hashCode =>
      pin.hashCode ^ token.hashCode ^ uri.hashCode ^ expiresAtUnix.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PairingInfoDto &&
          runtimeType == other.runtimeType &&
          pin == other.pin &&
          token == other.token &&
          uri == other.uri &&
          expiresAtUnix == other.expiresAtUnix;
}

/// One incoming stream.
class SourceDto {
  /// Stream id (use it with the `hub_set_*` functions).
  final int streamId;

  /// Sender device id.
  final String deviceId;

  /// Sender device name.
  final String deviceName;

  /// Stream label ("System audio", an app name...).
  final String label;

  /// Sender platform.
  final String platform;

  /// Linear gain 0.0..=4.0.
  final double gain;

  /// Muted on the hub.
  final bool muted;

  /// Priority source (ducks the others).
  final bool priority;

  /// Packets received within the last 2 s.
  final bool active;

  /// Loss after FEC over the last second, percent.
  final double lossPct;

  /// Interarrival jitter, ms.
  final double jitterMs;

  /// Jitter-buffer fill, ms.
  final double bufferMs;

  /// Estimated end-to-end latency, ms.
  final double latencyMs;

  /// Post-gain level, dBFS (-120 = silence).
  final double levelDb;

  const SourceDto({
    required this.streamId,
    required this.deviceId,
    required this.deviceName,
    required this.label,
    required this.platform,
    required this.gain,
    required this.muted,
    required this.priority,
    required this.active,
    required this.lossPct,
    required this.jitterMs,
    required this.bufferMs,
    required this.latencyMs,
    required this.levelDb,
  });

  @override
  int get hashCode =>
      streamId.hashCode ^
      deviceId.hashCode ^
      deviceName.hashCode ^
      label.hashCode ^
      platform.hashCode ^
      gain.hashCode ^
      muted.hashCode ^
      priority.hashCode ^
      active.hashCode ^
      lossPct.hashCode ^
      jitterMs.hashCode ^
      bufferMs.hashCode ^
      latencyMs.hashCode ^
      levelDb.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SourceDto &&
          runtimeType == other.runtimeType &&
          streamId == other.streamId &&
          deviceId == other.deviceId &&
          deviceName == other.deviceName &&
          label == other.label &&
          platform == other.platform &&
          gain == other.gain &&
          muted == other.muted &&
          priority == other.priority &&
          active == other.active &&
          lossPct == other.lossPct &&
          jitterMs == other.jitterMs &&
          bufferMs == other.bufferMs &&
          latencyMs == other.latencyMs &&
          levelDb == other.levelDb;
}
