// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'sender.freezed.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

/// Browses for hubs until `stop_discovery` or until the Dart stream is cancelled. A new call
/// replaces (and closes) the previous discovery stream.
Stream<DiscoveryEventDto> discoverHubs() =>
    RustLib.instance.api.crateApiSenderDiscoverHubs();

/// Stops browsing and closes the discovery stream.
Future<void> stopDiscovery() =>
    RustLib.instance.api.crateApiSenderStopDiscovery();

/// Processes that can be captured individually (empty where unsupported).
Future<List<CaptureAppDto>> listCaptureApps() =>
    RustLib.instance.api.crateApiSenderListCaptureApps();

/// Starts streaming to a hub. Returns once the capture is open and the engine started; the
/// connection progress arrives through `sender_status` / `sender_events`.
///
/// Fails with "a sender is already running" while a sender is live. A sender that ended by
/// itself (`failed`, e.g. pairing required or a wrong PIN, or `stopped`) is stopped and
/// replaced, so after a pairing failure just call this again with the PIN.
Future<void> senderStart({required SenderStartDto request}) =>
    RustLib.instance.api.crateApiSenderSenderStart(request: request);

/// Stops the sender (no-op if none runs).
Future<void> senderStop() => RustLib.instance.api.crateApiSenderSenderStop();

/// Current sender status (`state: "idle"` when none runs).
Future<SenderStatusDto> senderStatus() =>
    RustLib.instance.api.crateApiSenderSenderStatus();

/// Subscribes to sender status updates: the current status right away, then one per engine
/// event (state changes, about once per second while streaming). The subscription lives
/// until the Dart stream is cancelled and survives sender restarts.
Stream<SenderStatusDto> senderEvents() =>
    RustLib.instance.api.crateApiSenderSenderEvents();

/// A process that can be captured on its own.
class CaptureAppDto {
  /// Process id.
  final int pid;

  /// Display name.
  final String name;

  const CaptureAppDto({required this.pid, required this.name});

  @override
  int get hashCode => pid.hashCode ^ name.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CaptureAppDto &&
          runtimeType == other.runtimeType &&
          pid == other.pid &&
          name == other.name;
}

@freezed
sealed class CaptureSourceDto with _$CaptureSourceDto {
  const CaptureSourceDto._();

  /// Everything this device plays.
  const factory CaptureSourceDto.system() = CaptureSourceDto_System;

  /// Everything this device plays except this app.
  const factory CaptureSourceDto.systemExcludingSelf() =
      CaptureSourceDto_SystemExcludingSelf;

  /// One process (and its children where supported).
  const factory CaptureSourceDto.process({
    /// Process id (from `list_capture_apps`).
    required int pid,
  }) = CaptureSourceDto_Process;

  /// A test tone.
  const factory CaptureSourceDto.tone({
    /// Frequency in Hz, 0 < f < 24000.
    required double freqHz,
  }) = CaptureSourceDto_Tone;

  /// PCM pushed by native code (Android `NativeBridge.pushPcm`) into feed `feed_id`, in
  /// exactly this format.
  const factory CaptureSourceDto.external_({
    /// Feed id shared with the native side.
    required int feedId,

    /// Sample rate of the pushed PCM (8000..=192000).
    required int sampleRate,

    /// Channels of the pushed PCM (1..=8).
    required int channels,
  }) = CaptureSourceDto_External;
}

@freezed
sealed class DiscoveryEventDto with _$DiscoveryEventDto {
  const DiscoveryEventDto._();

  /// A hub appeared or changed.
  const factory DiscoveryEventDto.found(HubInfoDto field0) =
      DiscoveryEventDto_Found;

  /// A hub disappeared.
  const factory DiscoveryEventDto.lost({
    /// Its device id.
    required String deviceId,
  }) = DiscoveryEventDto_Lost;
}

/// A hub found on the LAN.
class HubInfoDto {
  /// Hub device id (pass it as `SenderStartDto.hub_device_id`).
  final String deviceId;

  /// Hub display name.
  final String name;

  /// Resolved addresses (IPv4 first).
  final List<String> addrs;

  /// TCP control port.
  final int port;

  /// Hub platform.
  final String platform;

  /// The hub is paired with this device (no PIN needed).
  final bool trusted;

  const HubInfoDto({
    required this.deviceId,
    required this.name,
    required this.addrs,
    required this.port,
    required this.platform,
    required this.trusted,
  });

  @override
  int get hashCode =>
      deviceId.hashCode ^
      name.hashCode ^
      addrs.hashCode ^
      port.hashCode ^
      platform.hashCode ^
      trusted.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HubInfoDto &&
          runtimeType == other.runtimeType &&
          deviceId == other.deviceId &&
          name == other.name &&
          addrs == other.addrs &&
          port == other.port &&
          platform == other.platform &&
          trusted == other.trusted;
}

/// How to start a sender.
class SenderStartDto {
  /// Hub host name or IP; empty = find the hub by `hub_device_id` over mDNS.
  final String hubHost;

  /// Hub port; 0 = the port from the settings (the protocol default if that is 0 too).
  final int hubPort;

  /// Hub device id (from discovery or a trusted peer). When `hub_key` is `None`, the key of
  /// this trusted peer is pinned.
  final String? hubDeviceId;

  /// Hub static key, base64url (`PairingUriDto.hub_id`).
  final String? hubKey;

  /// PIN or token; required when the hub is not paired yet.
  final String? pairingSecret;

  /// What to capture.
  final CaptureSourceDto source;

  /// Label shown on the hub; empty = a default for the source.
  final String label;

  const SenderStartDto({
    required this.hubHost,
    required this.hubPort,
    this.hubDeviceId,
    this.hubKey,
    this.pairingSecret,
    required this.source,
    required this.label,
  });

  @override
  int get hashCode =>
      hubHost.hashCode ^
      hubPort.hashCode ^
      hubDeviceId.hashCode ^
      hubKey.hashCode ^
      pairingSecret.hashCode ^
      source.hashCode ^
      label.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SenderStartDto &&
          runtimeType == other.runtimeType &&
          hubHost == other.hubHost &&
          hubPort == other.hubPort &&
          hubDeviceId == other.hubDeviceId &&
          hubKey == other.hubKey &&
          pairingSecret == other.pairingSecret &&
          source == other.source &&
          label == other.label;
}

/// Sender state for the UI.
class SenderStatusDto {
  /// `idle` (no sender), `connecting`, `pairing`, `streaming`, `reconnecting`, `stopped`
  /// or `failed`.
  final String state;

  /// Reason when `failed`, else the last non-fatal error, if any.
  final String? error;

  /// Name of the connected hub, once known.
  final String? hubName;

  /// Current Opus bitrate (bit/s).
  final int bitrate;

  /// Loss reported by the hub, percent.
  final double lossPct;

  /// Control round-trip time, ms.
  final double rttMs;

  /// Capture level, dBFS (-120 = silence).
  final double levelDb;

  /// Linear gain the hub applies to this stream (1.0 = unchanged; set on the hub).
  final double hubGain;

  /// The hub muted this stream: it is not heard there although it is sent.
  final bool hubMuted;

  /// The hub made this stream a priority source (it ducks the others).
  final bool hubPriority;

  const SenderStatusDto({
    required this.state,
    this.error,
    this.hubName,
    required this.bitrate,
    required this.lossPct,
    required this.rttMs,
    required this.levelDb,
    required this.hubGain,
    required this.hubMuted,
    required this.hubPriority,
  });

  @override
  int get hashCode =>
      state.hashCode ^
      error.hashCode ^
      hubName.hashCode ^
      bitrate.hashCode ^
      lossPct.hashCode ^
      rttMs.hashCode ^
      levelDb.hashCode ^
      hubGain.hashCode ^
      hubMuted.hashCode ^
      hubPriority.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SenderStatusDto &&
          runtimeType == other.runtimeType &&
          state == other.state &&
          error == other.error &&
          hubName == other.hubName &&
          bitrate == other.bitrate &&
          lossPct == other.lossPct &&
          rttMs == other.rttMs &&
          levelDb == other.levelDb &&
          hubGain == other.hubGain &&
          hubMuted == other.hubMuted &&
          hubPriority == other.hubPriority;
}
